1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[23,23,23],[12,12,121]])

In [3]:
b=np.array([[12,23,233],[2323,2323,2323],[12,12,12]])


In [4]:
a
c= np.zeros((3,3))

In [5]:
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j]=a[i][j]+b[i][j]

In [6]:
c

array([[  13.,   25.,  236.],
       [2346., 2346., 2346.],
       [  24.,   24.,  133.]])

Write a Python Program to Multiply Two Matrices?

In [9]:
def multipication (a,b):
    A= a.shape
    B=b.shape
    X=np.zeros((A[0],B[1]))
    if A[1]==B[0]:
        for i in range(A[0]):
            for z in range(A[0]):
                q=0
                for j in range(A[1]):
                    q=q+a[z][j]*b[j][z]
                X[i][z]=q
        return X
    else:
        print("Multiplication is not possible")
multipication(a,b)
            

array([[ 4694., 54234., 32124.],
       [ 4694., 54234., 32124.],
       [ 4694., 54234., 32124.]])

Write a Python Program to Transpose a Matrix?

In [12]:
a
A=a.shape

In [13]:
d=np.zeros((A[1],A[0]))

In [15]:
for i in range(len(a)):
    for j in range(len(a[0])):
        d[j][i]=a[i][j]

In [16]:
d


array([[  1.,  23.,  12.],
       [  2.,  23.,  12.],
       [  3.,  23., 121.]])

In [17]:
a

array([[  1,   2,   3],
       [ 23,  23,  23],
       [ 12,  12, 121]])

Write a Python Program to Sort Words in Alphabetic Order?

In [25]:
s='dfegregegnegnenfirniuehwudwuyg'

In [26]:
s=''.join(sorted(s))

In [27]:
s

'ddeeeeeeffggggghiinnnnrruuuwwy'

Write a Python Program to Remove Punctuation From a String?

In [28]:
import string

In [41]:
Punctuation_char = set(string.punctuation)

In [44]:
s='ien3i45h89hfoiansxamp,SPald,/,;lkjdsfkgr.,,hgu'
Output = ''.join(i for i in s if i not in Punctuation_char)

In [45]:
Output

'ien3i45h89hfoiansxampSPaldlkjdsfkgrhgu'